# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AidATrade' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AidATrade
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxSwiftExt'
  pod 'KeyboardAvoidingView', '~> 2.0'
  pod 'SQLite.swift', '~> 0.11.4'

  target 'AidATradeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AidATradeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
